"""create devices table

Revision ID: 32c137c86f95
Revises: 399e91e6c9de
Create Date: 2026-07-04 14:04:31.754914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c137c86f95'
down_revision: Union[str, Sequence[str], None] = '399e91e6c9de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=False, comment='Unique hostname of the network device'),
    sa.Column('serial_number', sa.String(length=100), nullable=False, comment='Vendor serial number'),
    sa.Column('asset_tag', sa.String(length=100), nullable=True, comment='Internal asset tracking ID'),
    sa.Column('vendor', sa.Enum('CISCO', 'JUNIPER', 'ARISTA', 'PALO_ALTO', 'FORTINET', name='devicevendor'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.Enum('ROUTER', 'SWITCH', 'FIREWALL', 'LOAD_BALANCER', 'WIRELESS_CONTROLLER', name='devicetype'), nullable=False),
    sa.Column('os', sa.String(length=100), nullable=False),
    sa.Column('software_version', sa.String(length=50), nullable=False),
    sa.Column('management_ip', sa.String(length=45), nullable=False, comment='IPv4 or IPv6 management address'),
    sa.Column('management_mac', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('HEALTHY', 'DOWN', 'MAINTENANCE', 'UNKNOWN', name='devicestatus'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rack_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_hostname'), 'devices', ['hostname'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_management_ip'), 'devices', ['management_ip'], unique=True)
    op.create_index(op.f('ix_devices_serial_number'), 'devices', ['serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_serial_number'), table_name='devices')
    op.drop_index(op.f('ix_devices_management_ip'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_hostname'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
