"""create change requests table

Revision ID: 391608656e5e
Revises: c43cd46cb0d4
Create Date: 2026-07-20 13:19:01.851116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '391608656e5e'
down_revision: Union[str, Sequence[str], None] = 'c43cd46cb0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('change_requests', 'requested_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('change_requests', 'requested_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
