"""create interface links table

Revision ID: 8a82f83db800
Revises: 8b55b757aef5
Create Date: 2026-07-05 19:39:15.839993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a82f83db800'
down_revision: Union[str, Sequence[str], None] = '8b55b757aef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interface_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_interface_id', sa.Integer(), nullable=False),
    sa.Column('destination_interface_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.Enum('COPPER', 'FIBER', 'DAC', 'WIRELESS', 'VIRTUAL', name='linktype'), nullable=False),
    sa.Column('status', sa.Enum('UP', 'DOWN', 'DISABLED', name='linkstatus'), nullable=False),
    sa.Column('bandwidth', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('source_interface_id <> destination_interface_id', name='ck_interface_link_no_self_loop'),
    sa.ForeignKeyConstraint(['destination_interface_id'], ['interfaces.id'], ),
    sa.ForeignKeyConstraint(['source_interface_id'], ['interfaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_interface_id', 'destination_interface_id', name='uq_interface_link')
    )
    op.create_index(op.f('ix_interface_links_destination_interface_id'), 'interface_links', ['destination_interface_id'], unique=False)
    op.create_index(op.f('ix_interface_links_id'), 'interface_links', ['id'], unique=False)
    op.create_index(op.f('ix_interface_links_source_interface_id'), 'interface_links', ['source_interface_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interface_links_source_interface_id'), table_name='interface_links')
    op.drop_index(op.f('ix_interface_links_id'), table_name='interface_links')
    op.drop_index(op.f('ix_interface_links_destination_interface_id'), table_name='interface_links')
    op.drop_table('interface_links')
    # ### end Alembic commands ###
