"""create interfaces table

Revision ID: 8b55b757aef5
Revises: 32c137c86f95
Create Date: 2026-07-04 20:46:57.007207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b55b757aef5'
down_revision: Union[str, Sequence[str], None] = '32c137c86f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('interface_type', sa.Enum('ETHERNET', 'LOOPBACK', 'VLAN', 'PORT_CHANNEL', 'TUNNEL', name='interfacetype'), nullable=False),
    sa.Column('admin_status', sa.Enum('UP', 'DOWN', 'ADMIN_DOWN', name='interfacestatus'), nullable=False),
    sa.Column('oper_status', sa.Enum('UP', 'DOWN', 'ADMIN_DOWN', name='interfacestatus'), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('mtu', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interfaces_id'), 'interfaces', ['id'], unique=False)
    op.create_index(op.f('ix_interfaces_name'), 'interfaces', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interfaces_name'), table_name='interfaces')
    op.drop_index(op.f('ix_interfaces_id'), table_name='interfaces')
    op.drop_table('interfaces')
    # ### end Alembic commands ###
