"""create configurations table

Revision ID: b948734d62c6
Revises: 8a82f83db800
Create Date: 2026-07-05 20:25:53.222132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b948734d62c6'
down_revision: Union[str, Sequence[str], None] = '8a82f83db800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config_type', sa.Enum('RUNNING', 'STARTUP', name='configurationtype'), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'version', name='uq_device_configuration_version')
    )
    op.create_index(op.f('ix_configurations_checksum'), 'configurations', ['checksum'], unique=False)
    op.create_index(op.f('ix_configurations_device_id'), 'configurations', ['device_id'], unique=False)
    op.create_index(op.f('ix_configurations_id'), 'configurations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configurations_id'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_device_id'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_checksum'), table_name='configurations')
    op.drop_table('configurations')
    # ### end Alembic commands ###
