"""create change requests table

Revision ID: c43cd46cb0d4
Revises: b948734d62c6
Create Date: 2026-07-20 13:01:39.301773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c43cd46cb0d4'
down_revision: Union[str, Sequence[str], None] = 'b948734d62c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'DEPLOYED', 'ROLLED_BACK', name='changerequeststatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='changepriority'), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_requests_configuration_id'), 'change_requests', ['configuration_id'], unique=False)
    op.create_index(op.f('ix_change_requests_device_id'), 'change_requests', ['device_id'], unique=False)
    op.create_index(op.f('ix_change_requests_id'), 'change_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_requests_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_device_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_configuration_id'), table_name='change_requests')
    op.drop_table('change_requests')
    # ### end Alembic commands ###
