"""create audit logs table

Revision ID: f0400fe27d92
Revises: 391608656e5e
Create Date: 2026-07-20 15:09:09.155905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0400fe27d92'
down_revision: Union[str, Sequence[str], None] = '391608656e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
change_request_status = postgresql.ENUM(
    "DRAFT",
    "PENDING",
    "APPROVED",
    "REJECTED",
    "DEPLOYED",
    "ROLLED_BACK",
    name="changerequeststatus",
    create_type=False,
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_request_id', sa.Integer(), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATED', 'SUBMITTED', 'APPROVED', 'REJECTED', 'DEPLOYED', 'ROLLED_BACK', name='auditaction'), nullable=False),
    sa.Column(
    "old_status",
    change_request_status,
    nullable=False,
    ),

    sa.Column(
        "new_status",
        change_request_status,
        nullable=False,
    ),
        
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_change_request_id'), 'audit_logs', ['change_request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_change_request_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
